apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcli-deployment
spec:
  selector:
    matchLabels:
      app: petcli
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: petcli
        image: pijey03/springboot-petclinc
        ports:
        - containerPort: 80
