apiVersion: v1
kind: Service
metadata:
  name: petcli
  labels:
    app: petcli
spec:
  type: NodePort
  ports:
  - port: 5000
    name: "petcli-service"
    targetPort: 80
    nodePort: 31221 
  selector:
    app: petcli
